### ISSUE TITLE
Feed reloads every time I go back to it

### ISSUE THREAD

**Issue by theboomr** [nick-delirium/lemmy-fennec#1]
After tapping into a post, or going to the search tab or profile tab, then going back to the main feed, it always reloads the feed every time, making it pretty annoying to try and scroll the feed and tap on things here and there, since I lose my scrolling position every time I do that

**Comment by nick-delirium** [comment]
Sphagetti code fixed in [this commit](https://github.com/nick-delirium/lemmy-fennec/commit/cd61aead9a2e5eb8ced4b0d5705184f60964fe23); now feed and community feeds will stay separated from each other so they shouldn't reset/update when you don't expect them to do this (now feed updates if theres 0 posts, filters changed or you refresh manually)

**Comment by nick-delirium** [comment]
Ok, should be fixed with [0.0.3-rc release](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.0.3-rc), don't hesitate to reopen if this will still happen.
