### ISSUE TITLE
View images full screen, and zoom in

### ISSUE THREAD

**Issue by nazaradeh** [nick-delirium/lemmy-fennec#10]
Right now images can only be viewed either in their reduced size in the feed, or full size when you click on it (but it's obstructed by the UI, and you need to scroll up and down to view the image).

It'd be nice to be able to just view the image full screen without UI obstructing it, and being able to zoom into the image.

**Comment by nick-delirium** [comment]
Its already included in my next commit, I just need to polish it a little bit and refactor Post component, because its getting too complicated to read. Don't hesitate to tell more about things you would like to see. I also [created a sublemmy](https://lemmy.world/c/fennec) if it makes it easier to talk about this app.

**Comment by nick-delirium** [comment]
Included in latest release
