### ISSUE TITLE
in communities with not a lot of posts scrolling just keeps repeating posts

### ISSUE THREAD

**Issue by ContentSpy** [nick-delirium/lemmy-fennec#15]
When you keep scrolling down you just get the same posts over and over instead of the scroll stopping when you reach the end (happens regardless of the sort type)

Example: 

https://github.com/nick-delirium/lemmy-fennec/assets/91404729/b5835a85-bd42-467e-aada-4978fd20c148

Pay attention to the posts with pictures

**Comment by nick-delirium** [comment]
Looks like it was an error inside community feed state (I always fetched 1st page no matter what... Time to write tests I guess)

Will be fixed in today's build.

Thank you for your help @ContentSpy btw, its always great to have a fresh eye on your app to test stuff I wouldn't think off because I'm too busy adding new things 👍

**Comment by ContentSpy** [comment]
> Looks like it was an error inside community feed state (I always fetched 1st page no matter what... Time to write tests I guess)
> 
> Will be fixed in today's build.
> 
> Thank you for your help @ContentSpy btw, its always great to have a fresh eye on your app to test stuff I wouldn't think off because I'm too busy adding new things 👍

Happy to help

**Comment by nick-delirium** [comment]
[Fixed](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.0.1-alpha.2)
